/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as LivresRouteImport } from './routes/livres'
import { Route as OrganisationsRouteImport } from './routes/organisations'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const LivresRoute = LivresRouteImport.update({
  id: '/livres',
  path: '/livres',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsRoute = OrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/formations': typeof FormationsRoute
  '/livres': typeof LivresRoute
  '/organisations': typeof OrganisationsRoute
  '/panier': typeof PanierRoute
  '/realisations': typeof RealisationsRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/formations': typeof FormationsRoute
  '/livres': typeof LivresRoute
  '/organisations': typeof OrganisationsRoute
  '/panier': typeof PanierRoute
  '/realisations': typeof RealisationsRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/formations': typeof FormationsRoute
  '/livres': typeof LivresRoute
  '/organisations': typeof OrganisationsRoute
  '/panier': typeof PanierRoute
  '/realisations': typeof RealisationsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/boutique'
    | '/contact'
    | '/experiences'
    | '/formations'
    | '/livres'
    | '/organisations'
    | '/panier'
    | '/realisations'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/boutique'
    | '/contact'
    | '/experiences'
    | '/formations'
    | '/livres'
    | '/organisations'
    | '/panier'
    | '/realisations'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/boutique'
    | '/contact'
    | '/experiences'
    | '/formations'
    | '/livres'
    | '/organisations'
    | '/panier'
    | '/realisations'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRoute
  AuthRoute: typeof AuthRoute
  BoutiqueRoute: typeof BoutiqueRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FormationsRoute: typeof FormationsRoute
  LivresRoute: typeof LivresRoute
  OrganisationsRoute: typeof OrganisationsRoute
  PanierRoute: typeof PanierRoute
  RealisationsRoute: typeof RealisationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livres': {
      id: '/livres'
      path: '/livres'
      fullPath: '/livres'
      preLoaderRoute: typeof LivresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations': {
      id: '/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof OrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRoute,
  AuthRoute: AuthRoute,
  BoutiqueRoute: BoutiqueRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRoute,
  FormationsRoute: FormationsRoute,
  LivresRoute: LivresRoute,
  OrganisationsRoute: OrganisationsRoute,
  PanierRoute: PanierRoute,
  RealisationsRoute: RealisationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
